"""Report image limits — advanced templates allow more attachments than standard."""

from app.modules.procedures.models import (
    REPORT_TEMPLATE_KEY_CAPSULE,
    REPORT_TEMPLATE_KEY_COLONOSCOPY_V2,
    REPORT_TEMPLATE_KEY_ENTEROSCOPY,
    REPORT_TEMPLATE_KEY_EMR,
    REPORT_TEMPLATE_KEY_ERCP,
    REPORT_TEMPLATE_KEY_ESD,
    REPORT_TEMPLATE_KEY_EUS,
    REPORT_TEMPLATE_KEY_FLEX_SIG_V2,
    REPORT_TEMPLATE_KEY_PROCTOSCOPY_V2,
    REPORT_TEMPLATE_KEY_UPPER_GI_V2,
)

ADVANCED_REPORT_TEMPLATE_KEYS = (
    REPORT_TEMPLATE_KEY_ERCP,
    REPORT_TEMPLATE_KEY_EUS,
    REPORT_TEMPLATE_KEY_CAPSULE,
    REPORT_TEMPLATE_KEY_ENTEROSCOPY,
    REPORT_TEMPLATE_KEY_EMR,
    REPORT_TEMPLATE_KEY_ESD,
)

STANDARD_REPORT_TEMPLATE_KEYS = (
    REPORT_TEMPLATE_KEY_UPPER_GI_V2,
    REPORT_TEMPLATE_KEY_COLONOSCOPY_V2,
    REPORT_TEMPLATE_KEY_FLEX_SIG_V2,
    REPORT_TEMPLATE_KEY_PROCTOSCOPY_V2,
)

MAX_IMAGES_ADVANCED = 8
MAX_IMAGES_STANDARD = 6

ALLOWED_IMAGE_CONTENT_TYPES = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
}


def max_images_for_template(template_key: str) -> int:
    if template_key in ADVANCED_REPORT_TEMPLATE_KEYS:
        return MAX_IMAGES_ADVANCED
    return MAX_IMAGES_STANDARD
