"""Patient Journey constants."""

from __future__ import annotations

FOLLOWUP_STATUS_PLANNED = "planned"
FOLLOWUP_STATUS_ACTIVE = "active"
FOLLOWUP_STATUS_COMPLETED = "completed"
FOLLOWUP_STATUS_CANCELLED = "cancelled"
FOLLOWUP_STATUS_MISSED = "missed"

ALL_FOLLOWUP_STATUSES = (
    FOLLOWUP_STATUS_PLANNED,
    FOLLOWUP_STATUS_ACTIVE,
    FOLLOWUP_STATUS_COMPLETED,
    FOLLOWUP_STATUS_CANCELLED,
    FOLLOWUP_STATUS_MISSED,
)

OUTCOME_IMPROVED = "improved"
OUTCOME_STABLE = "stable"
OUTCOME_WORSENED = "worsened"
OUTCOME_COMPLICATION = "complication"
OUTCOME_REFERRED = "referred"
OUTCOME_ADMITTED = "admitted"
OUTCOME_DISCHARGED = "discharged"
OUTCOME_LOST_TO_FOLLOWUP = "lost_to_follow_up"
OUTCOME_DEATH = "death"

ALL_OUTCOMES = (
    OUTCOME_IMPROVED,
    OUTCOME_STABLE,
    OUTCOME_WORSENED,
    OUTCOME_COMPLICATION,
    OUTCOME_REFERRED,
    OUTCOME_ADMITTED,
    OUTCOME_DISCHARGED,
    OUTCOME_LOST_TO_FOLLOWUP,
    OUTCOME_DEATH,
)

SUMMARY_STATUS_DRAFT = "draft"
SUMMARY_STATUS_APPROVED = "approved"
SUMMARY_STATUS_REJECTED = "rejected"

NEXT_ACTION_CONTINUE = "continue"
NEXT_ACTION_MODIFY = "modify"
NEXT_ACTION_ESCALATE = "escalate"
NEXT_ACTION_CLOSE = "close_encounter"

ALL_NEXT_ACTIONS = (
    NEXT_ACTION_CONTINUE,
    NEXT_ACTION_MODIFY,
    NEXT_ACTION_ESCALATE,
    NEXT_ACTION_CLOSE,
)

TIMELINE_ENCOUNTER = "encounter"
TIMELINE_ASSESSMENT = "assessment"
TIMELINE_INVESTIGATION = "investigation"
TIMELINE_PROCEDURE = "procedure"
TIMELINE_REPORT = "report"
TIMELINE_MANAGEMENT_PLAN = "management_plan"
TIMELINE_INTERPRETATION = "interpretation"
TIMELINE_FOLLOWUP = "follow_up"
TIMELINE_OUTCOME = "outcome"

AUDIT_PREFIX = "patient_journey"

CONFIDENCE_HIGH = "high"
CONFIDENCE_MEDIUM = "medium"
CONFIDENCE_LOW = "low"
