"""Research study registry constants — Sprint 6C."""

STUDY_STATUS_DRAFT = "draft"
STUDY_STATUS_ACTIVE = "active"
STUDY_STATUS_RECRUITING = "recruiting"
STUDY_STATUS_CLOSED = "closed"
STUDY_STATUS_ARCHIVED = "archived"

ALL_STUDY_STATUSES = (
    STUDY_STATUS_DRAFT,
    STUDY_STATUS_ACTIVE,
    STUDY_STATUS_RECRUITING,
    STUDY_STATUS_CLOSED,
    STUDY_STATUS_ARCHIVED,
)

CASE_STATUS_SCREENED = "screened"
CASE_STATUS_ENROLLED = "enrolled"
CASE_STATUS_ACTIVE = "active"
CASE_STATUS_COMPLETE = "complete"
CASE_STATUS_WITHDRAWN = "withdrawn"
CASE_STATUS_EXCLUDED = "excluded"

ALL_CASE_STATUSES = (
    CASE_STATUS_SCREENED,
    CASE_STATUS_ENROLLED,
    CASE_STATUS_ACTIVE,
    CASE_STATUS_COMPLETE,
    CASE_STATUS_WITHDRAWN,
    CASE_STATUS_EXCLUDED,
)

SCREENING_ELIGIBLE = "eligible"
SCREENING_INELIGIBLE = "ineligible"
SCREENING_PENDING = "pending"

ASSIGNMENT_PI = "principal_investigator"
ASSIGNMENT_REVIEWER = "reviewer"
ASSIGNMENT_COORDINATOR = "coordinator"

LOG_ACTION_SCREENED = "screened"
LOG_ACTION_ENROLLED = "enrolled"
LOG_ACTION_WITHDRAWN = "withdrawn"
LOG_ACTION_REVIEWED = "reviewed"
LOG_ACTION_EXCLUDED = "excluded"

EXPORT_FORMAT_CSV = "csv"
EXPORT_FORMAT_XLSX = "xlsx"
