"""Clinical AI constants — infrastructure identifiers only."""

from __future__ import annotations

PROMPT_CLINICAL_REASONING = "clinical_reasoning"
PROMPT_DIFFERENTIAL_DIAGNOSIS = "differential_diagnosis"
PROMPT_GUIDELINE_LOOKUP = "guideline_lookup"
PROMPT_REPORT_ASSISTANCE = "report_assistance"
PROMPT_PROCEDURE_ASSISTANCE = "procedure_assistance"
PROMPT_TEACHING_MODE = "teaching_mode"
PROMPT_RESEARCH_MODE = "research_mode"

ALL_PROMPT_TYPES = (
    PROMPT_CLINICAL_REASONING,
    PROMPT_DIFFERENTIAL_DIAGNOSIS,
    PROMPT_GUIDELINE_LOOKUP,
    PROMPT_REPORT_ASSISTANCE,
    PROMPT_PROCEDURE_ASSISTANCE,
    PROMPT_TEACHING_MODE,
    PROMPT_RESEARCH_MODE,
)

PROVIDER_OPENAI = "openai"
PROVIDER_CLAUDE = "claude"
PROVIDER_GEMINI = "gemini"
PROVIDER_LOCAL = "local"
PROVIDER_NULL = "null"

ALL_PROVIDER_KEYS = (
    PROVIDER_OPENAI,
    PROVIDER_CLAUDE,
    PROVIDER_GEMINI,
    PROVIDER_LOCAL,
    PROVIDER_NULL,
)

SESSION_PENDING = "pending"
SESSION_RUNNING = "running"
SESSION_COMPLETED = "completed"
SESSION_FAILED = "failed"
SESSION_CANCELLED = "cancelled"

ALL_SESSION_STATUSES = (
    SESSION_PENDING,
    SESSION_RUNNING,
    SESSION_COMPLETED,
    SESSION_FAILED,
    SESSION_CANCELLED,
)

CONTEXT_CLINICAL_HISTORY = "clinical_history"
CONTEXT_CLINICAL_REGISTRY = "clinical_registry"
CONTEXT_LABORATORY = "laboratory"
CONTEXT_IMAGING = "imaging"
CONTEXT_PROCEDURES = "procedures"
CONTEXT_REPORTS = "reports"
CONTEXT_KNOWLEDGE_OBJECTS = "knowledge_objects"
CONTEXT_RESEARCH = "research"

ALL_CONTEXT_SOURCES = (
    CONTEXT_CLINICAL_HISTORY,
    CONTEXT_CLINICAL_REGISTRY,
    CONTEXT_LABORATORY,
    CONTEXT_IMAGING,
    CONTEXT_PROCEDURES,
    CONTEXT_REPORTS,
    CONTEXT_KNOWLEDGE_OBJECTS,
    CONTEXT_RESEARCH,
)

PERM_VIEW = "clinical_ai:view"
PERM_USE = "clinical_ai:use"
PERM_CONFIGURE = "clinical_ai:configure"

SECTION_NARRATIVE = "narrative"
SECTION_BULLET_LIST = "bullet_list"
SECTION_TABLE = "table"
SECTION_STRUCTURED = "structured_section"
SECTION_RECOMMENDATIONS = "recommendations"
SECTION_REFERENCES = "references"

AUDIT_ACTION_PREFIX = "clinical_ai"
