"""Clinical Governance constants — Sprint 7D."""

# Incident categories
INCIDENT_PATIENT_ID = "patient_identification_error"
INCIDENT_WRONG_PROCEDURE = "wrong_procedure"
INCIDENT_EQUIPMENT = "equipment_failure"
INCIDENT_SEDATION = "sedation_complication"
INCIDENT_BLEEDING = "bleeding"
INCIDENT_PERFORATION = "perforation"
INCIDENT_SCOPE_DAMAGE = "scope_damage"
INCIDENT_MEDICATION = "medication_error"
INCIDENT_NEAR_MISS = "near_miss"
INCIDENT_OTHER = "other"

ALL_INCIDENT_CATEGORIES = (
    INCIDENT_PATIENT_ID,
    INCIDENT_WRONG_PROCEDURE,
    INCIDENT_EQUIPMENT,
    INCIDENT_SEDATION,
    INCIDENT_BLEEDING,
    INCIDENT_PERFORATION,
    INCIDENT_SCOPE_DAMAGE,
    INCIDENT_MEDICATION,
    INCIDENT_NEAR_MISS,
    INCIDENT_OTHER,
)

SEVERITY_MINOR = "minor"
SEVERITY_MODERATE = "moderate"
SEVERITY_MAJOR = "major"
SEVERITY_CRITICAL = "critical"

ALL_SEVERITIES = (SEVERITY_MINOR, SEVERITY_MODERATE, SEVERITY_MAJOR, SEVERITY_CRITICAL)

INCIDENT_OPEN = "open"
INCIDENT_UNDER_REVIEW = "under_review"
INCIDENT_CLOSED = "closed"

ALL_INCIDENT_STATUSES = (INCIDENT_OPEN, INCIDENT_UNDER_REVIEW, INCIDENT_CLOSED)

# M&M
MM_SCHEDULED = "scheduled"
MM_PRESENTED = "presented"
MM_CLOSED = "closed"

ALL_MM_STATUSES = (MM_SCHEDULED, MM_PRESENTED, MM_CLOSED)

# Audit projects
AUDIT_PLANNED = "planned"
AUDIT_IN_PROGRESS = "in_progress"
AUDIT_COMPLETED = "completed"
AUDIT_ARCHIVED = "archived"

ALL_AUDIT_STATUSES = (AUDIT_PLANNED, AUDIT_IN_PROGRESS, AUDIT_COMPLETED, AUDIT_ARCHIVED)

# Checklist types
CHECKLIST_WHO = "who_surgical"
CHECKLIST_ENDOSCOPY_SAFETY = "endoscopy_safety"
CHECKLIST_SEDATION = "sedation"
CHECKLIST_REPROCESSING = "reprocessing"

ALL_CHECKLIST_TYPES = (CHECKLIST_WHO, CHECKLIST_ENDOSCOPY_SAFETY, CHECKLIST_SEDATION, CHECKLIST_REPROCESSING)

# Document control
DOC_SOP = "sop"
DOC_PROTOCOL = "protocol"
DOC_POLICY = "policy"

ALL_DOCUMENT_TYPES = (DOC_SOP, DOC_PROTOCOL, DOC_POLICY)

DOC_DRAFT = "draft"
DOC_ACTIVE = "active"
DOC_SUPERSEDED = "superseded"

ALL_DOCUMENT_STATUSES = (DOC_DRAFT, DOC_ACTIVE, DOC_SUPERSEDED)
