"""EMR and ESD structured report vocabulary seeds (Sprint 4H)."""

EMR_ESD_VOCABULARY_SEED = {
    "emr_esd_indication_category": [
        ("resection_lgd", "Resection — low-grade dysplasia / adenoma", 10),
        ("resection_hgd", "Resection — high-grade dysplasia / intramucosal cancer", 20),
        ("resection_smp", "Resection — submucosal lesion (SM1–2)", 30),
        ("recurrence", "Recurrence at prior resection site", 40),
        ("staging", "Staging / pre-ESD assessment", 50),
        ("other", "Other / specify in detail", 99),
    ],
    "emr_esd_organ": [
        ("esophagus", "Esophagus", 10),
        ("stomach", "Stomach", 20),
        ("duodenum", "Duodenum", 30),
        ("colon", "Colon", 40),
        ("rectum", "Rectum", 50),
    ],
    "emr_esd_segment": [
        ("esophagus_upper", "Esophagus — upper third", 10),
        ("esophagus_mid", "Esophagus — middle third", 20),
        ("esophagus_lower", "Esophagus — lower third", 30),
        ("gastroesophageal_junction", "Gastroesophageal junction", 40),
        ("stomach_fundus", "Stomach — fundus", 50),
        ("stomach_body", "Stomach — body", 60),
        ("stomach_antrum", "Stomach — antrum", 70),
        ("duodenum_bulb", "Duodenum — bulb", 80),
        ("duodenum_d2", "Duodenum — D2", 90),
        ("cecum", "Colon — caecum", 100),
        ("ascending", "Colon — ascending", 110),
        ("transverse", "Colon — transverse", 120),
        ("descending", "Colon — descending", 130),
        ("sigmoid", "Colon — sigmoid", 140),
        ("rectum", "Rectum", 150),
        ("anal_canal", "Anal canal", 160),
    ],
    "emr_esd_scope_type": [
        ("standard_gastroscope", "Standard gastroscope", 10),
        ("therapeutic_gastroscope", "Therapeutic gastroscope", 20),
        ("standard_colonoscope", "Standard colonoscope", 30),
        ("pediatric_colonoscope", "Paediatric colonoscope", 40),
        ("ultra_slim", "Ultra-slim endoscope", 50),
    ],
    "paris_morphology": [
        ("0_ip", "0-Ip (pedunculated)", 10),
        ("0_isp", "0-Isp (subpedunculated)", 20),
        ("0_isa", "0-Is (sessile)", 30),
        ("0_iia", "0-IIa (flat elevated)", 40),
        ("0_iib", "0-IIb (flat)", 50),
        ("0_iic", "0-IIc (depressed)", 60),
        ("0_iii", "0-III (excavated)", 70),
        ("lsl_ge_20mm", "Laterally spreading lesion ≥ 20 mm", 80),
    ],
    "nice_classification": [
        ("type1", "Type 1 — hyperplastic / serrated", 10),
        ("type2", "Type 2 — adenoma (low risk)", 20),
        ("type3", "Type 3 — adenoma (high risk / deep)", 30),
    ],
    "jnet_classification": [
        ("type1", "JNET 1 — non-neoplastic", 10),
        ("type2a", "JNET 2A — low-grade adenoma", 20),
        ("type2b", "JNET 2B — high-grade / intramucosal", 30),
        ("type3", "JNET 3 — deep submucosal invasion suspected", 40),
    ],
    "lifting_assessment": [
        ("complete", "Complete lift", 10),
        ("partial", "Partial lift", 20),
        ("non_lifting", "Non-lifting sign", 30),
        ("not_tested", "Not tested", 40),
    ],
    "lift_solution": [
        ("saline", "Normal saline", 10),
        ("saline_epinephrine", "Saline + epinephrine", 20),
        ("hyaluronic_acid", "Hyaluronic acid", 30),
        ("glycerol", "Glycerol / succinylated gelatin", 40),
        ("mixed", "Mixed / other", 99),
    ],
    "emr_resection_technique": [
        ("cold_snare", "Cold snare", 10),
        ("hot_snare", "Hot snare", 20),
        ("underwater_emr", "Underwater EMR", 30),
        ("cap_assisted", "Cap-assisted EMR", 40),
        ("band_ligation_emr", "Band ligation EMR", 50),
        ("other", "Other", 99),
    ],
    "emr_snare_type": [
        ("standard", "Standard snare", 10),
        ("braided", "Braided snare", 20),
        ("stiff", "Stiff snare", 30),
        ("crescent", "Crescent snare", 40),
        ("not_applicable", "Not applicable", 99),
    ],
    "esd_marking_method": [
        ("coagulation", "Coagulation marking", 10),
        ("snare_marking", "Snare marking", 20),
        ("tattoo", "Tattoo / India ink", 30),
        ("none", "None", 99),
    ],
    "esd_knife_type": [
        ("it_knife", "IT-knife", 10),
        ("it_knife_nano", "IT-knife nano", 20),
        ("dual_knife", "Dual knife", 30),
        ("hook_knife", "Hook knife", 40),
        ("flush_knife", "Flush knife", 50),
        ("sb_knife", "SB knife", 60),
        ("clutch_cutter", "Clutch cutter", 70),
        ("other", "Other", 99),
    ],
    "esd_dissection_plane": [
        ("submucosal", "Submucosal plane", 10),
        ("muscularis_propria", "Muscularis propria (intentional)", 20),
        ("not_applicable", "Not applicable", 99),
    ],
    "defect_closure_method": [
        ("none", "None required", 10),
        ("clips", "Through-the-scope clips", 20),
        ("otsc", "Over-the-scope clip (OTSC)", 30),
        ("suture", "Endoscopic suturing", 40),
        ("other", "Other", 99),
    ],
    "resection_complication_type": [
        ("bleeding", "Bleeding", 10),
        ("perforation", "Perforation", 20),
        ("post_polypectomy_syndrome", "Post-polypectomy syndrome", 30),
        ("aspiration", "Aspiration", 40),
        ("cardiorespiratory", "Cardiorespiratory event", 50),
        ("other", "Other", 99),
    ],
    "hemostasis_method": [
        ("clips", "Clips", 10),
        ("coagulation", "Coagulation / APC", 20),
        ("injection", "Injection therapy", 30),
        ("otsc", "OTSC", 40),
        ("none", "None", 99),
    ],
    "expected_histology": [
        ("adenoma_lgd", "Adenoma — low-grade", 10),
        ("adenoma_hgd", "Adenoma — high-grade", 20),
        ("intramucosal_cancer", "Intramucosal carcinoma", 30),
        ("submucosal_cancer", "Submucosal carcinoma", 40),
        ("serrated", "Serrated lesion", 50),
        ("pending", "Pending", 60),
    ],
    "r_resection_status": [
        ("r0", "R0 — macroscopic complete", 10),
        ("r1", "R1 — macroscopic incomplete", 20),
        ("rx", "Rx — cannot assess", 30),
        ("pending_histology", "Pending histology", 40),
    ],
}
