"""Upper GI structured report — vocabulary seed data."""

UPPER_GI_V2_VOCABULARY_SEED = {
    "upper_gi_indication_category": [
        ("dyspepsia", "Dyspepsia", 10),
        ("gi_bleeding", "GI bleeding / anaemia", 20),
        ("dysphagia", "Dysphagia", 30),
        ("reflux", "GORD / reflux symptoms", 40),
        ("barrett_surveillance", "Barrett's surveillance", 50),
        ("varices", "Variceal surveillance / bleeding", 60),
        ("nutrition", "Nutritional support (PEG)", 70),
        ("foreign_body", "Foreign body", 80),
        ("other", "Other / specify in detail", 99),
    ],
    "upper_gi_scope_type": [
        ("standard_gastroscope", "Standard gastroscope", 10),
        ("therapeutic_gastroscope", "Therapeutic gastroscope", 20),
        ("ultra_slim", "Ultra-slim scope", 30),
    ],
    "upper_gi_finding_type": [
        ("normal", "Normal", 10),
        ("oesophagitis", "Oesophagitis", 20),
        ("barretts", "Barrett's oesophagus", 30),
        ("varices", "Varices", 40),
        ("ulcer", "Ulcer", 50),
        ("mass", "Mass / lesion", 60),
        ("stricture", "Stricture", 70),
        ("hiatus_hernia", "Hiatus hernia", 80),
        ("gastritis", "Gastritis", 90),
        ("polyp", "Polyp", 100),
        ("other", "Other", 99),
    ],
    "upper_gi_intervention_type": [
        ("biopsy", "Biopsy", 10),
        ("polypectomy", "Polypectomy", 20),
        ("emr", "EMR", 30),
        ("esd", "ESD", 40),
        ("band_ligation", "Variceal band ligation", 50),
        ("apc", "APC", 60),
        ("injection_therapy", "Injection therapy", 70),
        ("hemostasis", "Hemostasis", 80),
        ("dilatation", "Dilatation", 90),
        ("foreign_body_removal", "Foreign body removal", 100),
        ("peg", "PEG insertion", 110),
        ("peg_replacement", "PEG replacement", 120),
        ("peg_removal", "PEG removal", 130),
        ("clip", "Clip placement", 140),
        ("stent", "Stent placement", 150),
        ("other", "Other", 99),
    ],
}
