"""Knowledge Library — stable object type identifiers (specialty-agnostic)."""

OBJECT_TYPE_DISEASE = "disease"
OBJECT_TYPE_SYMPTOM = "symptom"
OBJECT_TYPE_COMPLAINT = "complaint"
OBJECT_TYPE_HISTORY_QUESTION = "history_question"
OBJECT_TYPE_PHYSICAL_EXAMINATION = "physical_examination_finding"
OBJECT_TYPE_DIFFERENTIAL = "differential_diagnosis"
OBJECT_TYPE_INVESTIGATION = "investigation"
OBJECT_TYPE_SCORE = "clinical_score"
OBJECT_TYPE_GUIDELINE = "guideline"
OBJECT_TYPE_MANAGEMENT = "management_recommendation"
OBJECT_TYPE_TEACHING = "teaching_note"
OBJECT_TYPE_REFERENCE = "reference"
OBJECT_TYPE_CDS_RULE = "cds_rule"

ALL_OBJECT_TYPES = (
    OBJECT_TYPE_DISEASE,
    OBJECT_TYPE_SYMPTOM,
    OBJECT_TYPE_COMPLAINT,
    OBJECT_TYPE_HISTORY_QUESTION,
    OBJECT_TYPE_PHYSICAL_EXAMINATION,
    OBJECT_TYPE_DIFFERENTIAL,
    OBJECT_TYPE_INVESTIGATION,
    OBJECT_TYPE_SCORE,
    OBJECT_TYPE_GUIDELINE,
    OBJECT_TYPE_MANAGEMENT,
    OBJECT_TYPE_TEACHING,
    OBJECT_TYPE_REFERENCE,
    OBJECT_TYPE_CDS_RULE,
)

STATUS_DRAFT = "draft"
STATUS_PUBLISHED = "published"
STATUS_SUPERSEDED = "superseded"
STATUS_ARCHIVED = "archived"

ALL_STATUSES = (STATUS_DRAFT, STATUS_PUBLISHED, STATUS_SUPERSEDED, STATUS_ARCHIVED)

LINK_REFERENCES = "references"
LINK_APPLIES_TO = "applies_to"
LINK_DIFFERENTIAL_FOR = "differential_for"
LINK_RECOMMENDS = "recommends"
LINK_TEACHES = "teaches"

ALL_LINK_TYPES = (LINK_REFERENCES, LINK_APPLIES_TO, LINK_DIFFERENTIAL_FOR, LINK_RECOMMENDS, LINK_TEACHES)
