"""Department Operations constants — Sprint 7C."""

# Room status
ROOM_AVAILABLE = "available"
ROOM_OCCUPIED = "occupied"
ROOM_CLEANING = "cleaning"
ROOM_MAINTENANCE = "maintenance"
ROOM_OUT_OF_SERVICE = "out_of_service"

ALL_ROOM_STATUSES = (
    ROOM_AVAILABLE,
    ROOM_OCCUPIED,
    ROOM_CLEANING,
    ROOM_MAINTENANCE,
    ROOM_OUT_OF_SERVICE,
)

# Room types
ROOM_TYPE_GENERAL = "general"
ROOM_TYPE_ERCP = "ercp"
ROOM_TYPE_EUS = "eus"
ROOM_TYPE_RECOVERY = "recovery"
ROOM_TYPE_OTHER = "other"

ALL_ROOM_TYPES = (ROOM_TYPE_GENERAL, ROOM_TYPE_ERCP, ROOM_TYPE_EUS, ROOM_TYPE_RECOVERY, ROOM_TYPE_OTHER)

# Scope types
SCOPE_GASTRO = "gastroscope"
SCOPE_COLON = "colonoscope"
SCOPE_DUODENO = "duodenoscope"
SCOPE_ECHO = "echoendoscope"
SCOPE_PEDIATRIC = "pediatric"
SCOPE_OTHER = "other"

ALL_SCOPE_TYPES = (SCOPE_GASTRO, SCOPE_COLON, SCOPE_DUODENO, SCOPE_ECHO, SCOPE_PEDIATRIC, SCOPE_OTHER)

# Scope status
SCOPE_AVAILABLE = "available"
SCOPE_IN_PROCEDURE = "in_procedure"
SCOPE_AWAITING_CLEANING = "awaiting_cleaning"
SCOPE_CLEANING = "cleaning"
SCOPE_READY = "ready"
SCOPE_MAINTENANCE = "maintenance"
SCOPE_OUT_OF_SERVICE = "out_of_service"

ALL_SCOPE_STATUSES = (
    SCOPE_AVAILABLE,
    SCOPE_IN_PROCEDURE,
    SCOPE_AWAITING_CLEANING,
    SCOPE_CLEANING,
    SCOPE_READY,
    SCOPE_MAINTENANCE,
    SCOPE_OUT_OF_SERVICE,
)

# Reprocessing steps
REPROC_PROCEDURE_FINISHED = "procedure_finished"
REPROC_SENT_FOR_CLEANING = "sent_for_cleaning"
REPROC_LEAK_TEST = "leak_test"
REPROC_MANUAL_CLEANING = "manual_cleaning"
REPROC_HLD = "high_level_disinfection"
REPROC_DRYING = "drying"
REPROC_STORAGE = "storage"
REPROC_READY = "ready_again"

REPROCESSING_STEPS = (
    REPROC_PROCEDURE_FINISHED,
    REPROC_SENT_FOR_CLEANING,
    REPROC_LEAK_TEST,
    REPROC_MANUAL_CLEANING,
    REPROC_HLD,
    REPROC_DRYING,
    REPROC_STORAGE,
    REPROC_READY,
)

# Consumable categories
CONSUMABLE_STENT = "stent"
CONSUMABLE_SNARE = "snare"
CONSUMABLE_NEEDLE = "injection_needle"
CONSUMABLE_GUIDEWIRE = "guidewire"
CONSUMABLE_SPHINCTEROTOME = "sphincterotome"
CONSUMABLE_BALLOON = "balloon"
CONSUMABLE_CLIP = "clip"
CONSUMABLE_HEMOSTATIC = "hemostatic"
CONSUMABLE_BIOPSY_FORCEPS = "biopsy_forceps"
CONSUMABLE_CYTOLOGY_BRUSH = "cytology_brush"
CONSUMABLE_PEG_KIT = "peg_kit"
CONSUMABLE_DILATOR = "dilator"
CONSUMABLE_OTHER = "other"

ALL_CONSUMABLE_CATEGORIES = (
    CONSUMABLE_STENT,
    CONSUMABLE_SNARE,
    CONSUMABLE_NEEDLE,
    CONSUMABLE_GUIDEWIRE,
    CONSUMABLE_SPHINCTEROTOME,
    CONSUMABLE_BALLOON,
    CONSUMABLE_CLIP,
    CONSUMABLE_HEMOSTATIC,
    CONSUMABLE_BIOPSY_FORCEPS,
    CONSUMABLE_CYTOLOGY_BRUSH,
    CONSUMABLE_PEG_KIT,
    CONSUMABLE_DILATOR,
    CONSUMABLE_OTHER,
)

STOCK_USAGE = "usage"
STOCK_RECEIPT = "receipt"
STOCK_ADJUSTMENT = "adjustment"

# Waiting list
WL_ACTIVE = "active"
WL_SCHEDULED = "scheduled"
WL_COMPLETED = "completed"
WL_CANCELLED = "cancelled"

ALL_WAITING_LIST_STATUSES = (WL_ACTIVE, WL_SCHEDULED, WL_COMPLETED, WL_CANCELLED)

# Duty roster
SHIFT_DAY = "day"
SHIFT_EVENING = "evening"
SHIFT_ON_CALL = "on_call"
SHIFT_LEAVE = "leave"
SHIFT_BACKUP = "backup"

ALL_SHIFT_TYPES = (SHIFT_DAY, SHIFT_EVENING, SHIFT_ON_CALL, SHIFT_LEAVE, SHIFT_BACKUP)

# Announcements
ANN_NOTICE = "notice"
ANN_DEPARTMENT = "department"
ANN_HOLIDAY = "holiday"
ANN_EQUIPMENT = "equipment"
ANN_ACADEMIC = "academic"

ALL_ANNOUNCEMENT_CATEGORIES = (ANN_NOTICE, ANN_DEPARTMENT, ANN_HOLIDAY, ANN_EQUIPMENT, ANN_ACADEMIC)

ANN_PRIORITY_NORMAL = "normal"
ANN_PRIORITY_HIGH = "high"
ANN_PRIORITY_URGENT = "urgent"

# Messaging
MSG_DIRECT = "direct"
MSG_TEAM = "team"
MSG_DEPARTMENT = "department"

ALL_MESSAGE_SCOPES = (MSG_DIRECT, MSG_TEAM, MSG_DEPARTMENT)

# Generic resources
RESOURCE_ROOM = "room"
RESOURCE_EQUIPMENT = "equipment"
RESOURCE_SCOPE = "scope"
RESOURCE_COMPUTER = "computer"
RESOURCE_ULTRASOUND = "ultrasound"
RESOURCE_FLUOROSCOPY = "fluoroscopy"
RESOURCE_OTHER = "other"

ALL_RESOURCE_TYPES = (
    RESOURCE_ROOM,
    RESOURCE_EQUIPMENT,
    RESOURCE_SCOPE,
    RESOURCE_COMPUTER,
    RESOURCE_ULTRASOUND,
    RESOURCE_FLUOROSCOPY,
    RESOURCE_OTHER,
)

MAINTENANCE_SERVICE = "service"
MAINTENANCE_REPAIR = "repair"
